apiVersion: v1
kind: Pod
metadata:
  name: login-pod
  namespace: erl-ucsd
spec:
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
          - matchExpressions:
              - key: kubernetes.io/hostname
                operator: NotIn
                values:
                  - nautilus-ext-gpu01.fullerton.edu
                  - hcc-chase-shor-c4715.unl.edu
                  - hcc-nrp-shor-c5934.unl.edu
                  - knuron.calit2.optiputer.net
                  - k8s-3090-01.usd.edu
                  - k8s-3090-02.clemson.edu
                  - k8s-gen4-sm.calit2.optiputer.net
              - key: nvidia.com/gpu.product
                operator: In
                values:
                  - NVIDIA-GeForce-RTX-3090
                  - NVIDIA-GeForce-RTX-4090
                  - NVIDIA-RTX-A5000
                  - NVIDIA-RTX-A6000
  containers:
  - name: login-container
    image: gitlab-registry.nrp-nautilus.io/h1cao/vlmap:latest
    command: ["sleep", "infinity"]
    volumeMounts:
    - mountPath: /mnt
      name: erl-ucsd
    resources:
      limits:
        memory: "32G"
        cpu: "16"
  imagePullSecrets:
  - name: h1cao-pull-regcred
  restartPolicy: Never
  volumes:
    - name: erl-ucsd
      persistentVolumeClaim:
        claimName: erl-ucsd